### PR TITLE
Start Mocking up Shop UI

### PR DESCRIPTION
**Pull request by harolddavisjr**
Summary
-------------------------------------

Start Mocking up Shop UI:
* Via the main menu sks file
* Adding Assets
* Shop node should be located at `x: 0, y: -500`

Simulator Screen Recording - Apple Watch Series 5 - 40mm - 2021-08-04 at 17 54 00

### CODE REVIEW

**Comment by Sage-tech** [comment]
Ohh way to go Harold 🎊

**Comment by gagefonk** [comment]
agreed lookin good! the galactic starship trading post and exchange(my new name for it lol) is coming along nicely.

**Comment by harolddavisjr** [comment]
Thanks guys 😁😁😁lots of cool things down the line!

C9E572EF-3CA9-4980-8D48-F825B4C7389B

491E047A-5ED3-43E2-9915-14377E5C48A6

**Comment by harolddavisjr** [comment]
Thanks guys 😁😁😁

**Pull request merged**
